### testing api call

### user


### get user
GET http://localhost:8000/api/v1/users
Content-Type: application/json

### post user
 POST http://localhost:8000/api/v1/users/signup
 Content-Type: application/json
 
 {
  "name": "Bhaskar",
  "email": "d@gmail.com",
  "password":"1234567"
 }

### post user login
 POST http://localhost:8000/api/v1/users/login
 Content-Type: application/json
 
 {
  "email": "ab@gmail.com",
  "password":"12345"
 }
### get user email 
 GET http://localhost:8000/api/v1/users
 Content-Type: application/json
 
 {
  "name": "Bhaskar",
  "email": "ab@gmail.com",
  "password":"12345"
 }

### transactions: all private routes

### Post new transactions
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json

{
"type": "income",
"title": "salary",
"amount": "112",
"tdate": "08-04-2026"

}

