
### user

### get user
GET http://localhost:8000/api/v1/users
Content-Type: application/json

### post user login
 POST http://localhost:8000/api/v1/users/login
 Content-Type: application/json
 
 {
  "email": "ab@gmail.com",
  "password":"12345"
 }

### transactions: all private routes

### Post new transactions
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiQGdtYWlsLmNvbSIsImlhdCI6MTc4NTkwOTIwNywiZXhwIjoxNzg1OTk1NjA3fQ.ue0gx6FHlpyaOa7xKuX5AczOH99ugnOW5HgsDM9glfc

{
"type": "income",
"title": "salary",
"amount": "112",
"tdate": "08-04-2026"

}

#### Get all transactions
GET http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiQGdtYWlsLmNvbSIsImlhdCI6MTc4NTkwOTIwNywiZXhwIjoxNzg1OTk1NjA3fQ.ue0gx6FHlpyaOa7xKuX5AczOH99ugnOW5HgsDM9glfc

### delete transactions by a specific id
DELETE http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiQGdtYWlsLmNvbSIsImlhdCI6MTc4NTkwOTIwNywiZXhwIjoxNzg1OTk1NjA3fQ.ue0gx6FHlpyaOa7xKuX5AczOH99ugnOW5HgsDM9glfc

["6a43c41c90b640a030267cfb", "6a3cf220257eaa3ca3f92571"]